name: Release

on:
  push:
    branches:
      - "preprod"
      - "main"

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20
      - run: npm ci --force
      - run: npm run build
      - run: tar -czvf jmmc.tar.gz dist public package.json package-lock.json
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}